name: Print pull request context
#on: [workflow_dispatch, pull_request]
on:
  workflow_dispatch:
  pull_request:
    # Перечисляем Activity types
    # opened - открыли pull request
    # edited - отредактировали pull request
    # reopened - переоткрыли pull request
    types: [opened, edited, reopened]
jobs:
  print:
    runs-on: windows-latest
    steps:
      - name: Print context
        run: echo "${{ toJSON(github.event) }}"
